services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  TelegramBotBundle\Command\:
    resource: '../../Command/'
  TelegramBotBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  TelegramBotBundle\Handler\:
    resource: '../../Handler/'
  TelegramBotBundle\Controller\:
    resource: '../../Controller/'
  TelegramBotBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  TelegramBotBundle\Repository\:
    resource: '../../Repository/'
  TelegramBotBundle\Service\:
    resource: '../../Service/'
