services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  TelegramBotBundle\AdminMenu: ~

  # 如果确认要使用自动扫描、自动注册，建议尽可能将要扫描的目录路径收缩，不要设置那么大的范围
  TelegramBotBundle\Command\:
    resource: '../../Command/'
  TelegramBotBundle\Handler\:
    resource: '../../Handler/'
  TelegramBotBundle\Controller\:
    resource: '../../Controller/'
  TelegramBotBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  TelegramBotBundle\Repository\:
    resource: '../../Repository/'
  TelegramBotBundle\Service\:
    resource: '../../Service/'
